const PLAYER = {
  name:     'Nikita G.',
  fullName: 'Nikita Galochkin',
  handle:   'Player <span>Profile</span>',
  title:    'Sr. UE Programmer',
server:   'Da Nang · Remote',
  status:   'Available for Contract',
  stats: [
    { label: 'Prof. Experience',        value: '10+ yrs'},
    { label: 'AAA Experience',          value: '5 yrs' },
    { label: 'Titles Shipped',          value: '6' },
    { label: 'Engines',                 value: 'Unreal Engine, Unity'},
      { label: 'Primary Languages',       value: 'C++, C#, Python'}, 
      { label: 'Languages',                 value: 'Eng B1, Rus Native' },
    { label: 'Timezone',                value: 'Asia' },
  ],
};

const CAREER_OVERVIEW = {
  bio: 'Senior Unreal Engine programmer with 10+ years building gameplay, multiplayer, and AI systems across AAA and indie studios in Belarus, Russia, Thailand, and remote. Specialized in netcode architecture, GAS, and performance optimization — shipped titles on PC, console, and VR.',
};

const SKILLS = [
  { label: 'GAS',                tier: 1 },
  { label: 'CommonUI' },
  { label: 'HTN' },
  { label: 'EOS' },
  { label: 'WebSocket' },
  { label: 'Quic Protocol' },
  { label: 'GRPC · Protobuf' },
  { label: 'CI/CD' },
  { label: 'Easy Anti-Cheat' },
  { label: 'Sentry' },
  { label: 'Test Automation' },
  { label: 'Perforce / Git' },
  { label: 'Unreal Insights' },
  { label: 'Editor Tools' },
];

const PROJECTS = [
  {
    id:     'atone',
    name:   'Atone',
    tier:   'legendary',
    badge:  'aaa',
    status: { type: 'hold', label: '✕ Canceled' },
    date:   'Dec 2025 – 2026',
    role:   'Sr. Client Programmer',
    studio: 'GS Studio · Cyprus · Action-Adventure MMORPG · UE5 · 30+ projects · 20M+ players',
    desc:   'Large-scale action-adventure MMORPG built entirely in-house over 5 years. Desert/Middle-Eastern open world in UE5 with custom dedicated servers (70 CCU per layer), server-authoritative netcode, IRIS replication and Nanite geometry.',
    tags:   ['Quic', 'EOS', 'IRIS Replication', 'Network Refactor', 'Test Automation'],
    links:  [],
    gallery: [
      { type: 'image', src: 'media/atone/1.jpg', alt: 'Atone screenshot 1' },
      { type: 'image', src: 'media/atone/2.jpg', alt: 'Atone screenshot 2' },
      { type: 'image', src: 'media/atone/3.jpg', alt: 'Atone screenshot 3' },
      { type: 'image', src: 'media/atone/4.jpg', alt: 'Atone screenshot 4' },
      { type: 'image', src: 'media/atone/5.jpg', alt: 'Atone screenshot 5' },
    ],
  },
  {
    id:     'blood-of-heroes',
    name:   'Blood of Heroes',
    tier:   'legendary',
    badge:  'aaa',
    status: { type: 'win', label: '✓ Shipped' },
    date:   '2019 – 2022',
    role:   'Software Engineer',
    studio: 'Vizor Games · Minsk · 700+ team · PvP Melee Fighter · PC & Console',
    desc:   'Dark fantasy PvP melee arena fighter inspired by For Honor. Warriors battle in medieval Nordic arenas with directional combat and stamina mechanics. Released on PC — PS4/PS5 & Xbox in progress before cancellation.',
    tags:   ['GAS', 'Perf −27% CPU', 'Unreal Insights', 'Test Automation', 'Gauntlet'],
    links:  [{ label: 'Trailer', url: 'https://www.youtube.com/watch?v=k1dJ1VYJVNg' }],
    gallery: [
      { type: 'image',   src: 'media/blood-of-heroes/1.jpg', alt: 'Blood of Heroes screenshot 1' },
      { type: 'image',   src: 'media/blood-of-heroes/2.jpg', alt: 'Blood of Heroes screenshot 2' },
      { type: 'youtube', videoId: 'k1dJ1VYJVNg', alt: 'Blood of Heroes trailer' },
    ],
  },
  {
    id:     'boss-fighters',
    name:   'Boss Fighters',
    tier:   'rare',
    badge:  'aa',
    status: { type: 'win', label: '✓ Shipped' },
    date:   '2023 – 2025',
    role:   'Lead Programmer',
    studio: 'Pixward Games · Asymmetric VR-PC Multiplayer Shooter · Free to Play',
    desc:   'Asymmetrical multiplayer — VR player becomes the massive Boss, manipulating a physics sandbox arena. PC team plays as Fighters using strategy and environment to take it down.',
    tags:   ['Client-Server Arch', 'WebSocket', 'EOS', 'CI/CD', 'Anti-Cheat', 'Team Lead'],
    links:  [
      { label: 'Steam',   url: 'https://store.steampowered.com/app/1784650/BOSS_FIGHTERS/' },
      { label: 'Website', url: 'https://www.bossfighters.game/' },
    ],
    gallery: [
      { type: 'image',   src: 'media/boss-fighters/1.jpg', alt: 'Boss Fighters screenshot 1' },
      { type: 'image',   src: 'media/boss-fighters/2.jpg', alt: 'Boss Fighters screenshot 2' },
      { type: 'image',   src: 'media/boss-fighters/3.jpg', alt: 'Boss Fighters screenshot 3' },
      { type: 'youtube', videoId: 'TQRobo2zft8', alt: 'Boss Fighters trailer' },
    ],
  },
  {
    id:     'majestic',
    name:   'Open World Roleplay',
    tier:   'legendary',
    badge:  'aaa',
    status: { type: 'win', label: '✓ Shipped' },
    date:   '2025',
    role:   'Sr. Gameplay Programmer',
    studio: 'Majestic Games · London Studio · GTA-Style Roleplay · 500k+ players · NDA',
    desc:   'GTA-style open-world roleplay with deep progression and 500k+ active players. London studio title with a large existing codebase — shipped new systems into a live game.',
    tags:   ['CommonUI', 'Gameplay Systems', 'Editor Tools', 'UI Architecture', 'Interaction System'],
    links:  [],
    gallery: [
      { type: 'image',   src: 'media/majestic/1.jpg', alt: 'Majestic Roleplay screenshot 1' },
      { type: 'image',   src: 'media/majestic/2.jpg', alt: 'Majestic Roleplay screenshot 2' },
      { type: 'image',   src: 'media/majestic/3.jpg', alt: 'Majestic Roleplay screenshot 3' },
      { type: 'image',   src: 'media/majestic/4.jpg', alt: 'Majestic Roleplay screenshot 4' },
      { type: 'youtube', videoId: 'LxMnCSCFcz8', alt: 'Majestic Role Play trailer' },
    ],
  },
  {
    id:     'mygames',
    name:   'Open World MMORPG',
    tier:   'legendary',
    badge:  'aaa',
    status: { type: 'hold', label: '✕ Canceled' },
    date:   '2022 – 2023',
    role:   'Sr. AI Programmer',
    studio: 'MY.GAMES · Global · 1B+ users · Open World MMORPG · NDA',
    desc:   'Massive open-world MMORPG under MY.GAMES publishing. Hundreds of AI-driven NPCs navigating complex terrain — climbing, jumping, crowd simulation. Had canceled after 5 years.',
    tags:   ['AI / HTN', 'Crowd NPC', 'Navigation', 'Open World', 'Nav Automation'],
    links:  [],
    gallery: [
      { type: 'image', src: 'media/mygames/1.jpg', alt: 'Project screenshot 1' },
      { type: 'image', src: 'media/mygames/2.jpg', alt: 'Project screenshot 2' },
    ],
  },
  {
    id:     'loco-parentis',
    name:   'Loco Parentis',
    tier:   'rare',
    badge:  'aa',
    status: { type: 'win', label: '✓ Shipped' },
    date:   '2017 – 2019',
    role:   'Programmer',
    studio: 'GD Forge · Fair Games Studio · Kazan · Surreal Co-op VR Horror · PC & VR',
    desc:   'Surreal co-op VR+PC horror — help a girl find her mother in an endless, monster-filled building. Supports VR+VR, VR+PC, and PC+PC co-op combinations.',
    tags:   ['VR', 'Co-op', 'Horror', 'UE4'],
    links:  [{ label: 'Steam', url: 'https://store.steampowered.com/app/693800/Loco_Parentis/' }],
    gallery: [
      { type: 'image',   src: 'media/loco-parentis/1.jpg', alt: 'Loco Parentis screenshot 1' },
      { type: 'image',   src: 'media/loco-parentis/2.jpg', alt: 'Loco Parentis screenshot 2' },
      { type: 'image',   src: 'media/loco-parentis/3.jpg', alt: 'Loco Parentis screenshot 3' },
      { type: 'youtube', videoId: 'YHb0HB64ZqQ', alt: 'Loco Parentis trailer' },
    ],
  },
  {
    id:     'protocol',
    name:   'Protocol',
    tier:   'rare',
    badge:  'aa',
    status: { type: 'win', label: '✓ Shipped' },
    date:   '2016 – 2018',
    role:   'Programmer',
    studio: 'GD Forge · Fair Games Studio · Kazan · Sci-Fi Comedy Adventure · PC & VR',
    desc:   'Sci-fi comedy adventure with dark humour. Carry out the Protocol — a strict set of government rules for making first contact with an alien life form shot down in the Arctic Circle.',
    tags:   ['VR', 'Sci-Fi', 'Adventure', 'UE4'],
    links:  [{ label: 'Steam', url: 'https://store.steampowered.com/app/724490/Protocol/' }],
    gallery: [
      { type: 'image',   src: 'media/protocol/1.jpg', alt: 'Protocol screenshot 1' },
      { type: 'image',   src: 'media/protocol/2.jpg', alt: 'Protocol screenshot 2' },
      { type: 'image',   src: 'media/protocol/3.jpg', alt: 'Protocol screenshot 3' },
      { type: 'youtube', videoId: 'kJdMoBnWK5o', alt: 'Protocol trailer' },
    ],
  },
  {
    id:     'mages-mazes',
    name:   'Mages Mazes',
    tier:   'uncommon',
    badge:  'a',
    status: { type: 'win', label: '✓ Shipped' },
    date:   '2015 – 2017',
    role:   'Programmer',
    studio: 'GD Forge · Kazan · Mobile Online Rogue-like',
    desc:   'Mobile online rogue-like — fight monsters and other players in a magical, constantly changing dungeon. Find keys, unlock chests, collect rewards in an ever-shifting maze.',
    tags:   ['Mobile', 'Rogue-like', 'Online Multiplayer'],
    links:  [],
    gallery: [
      { type: 'youtube', videoId: 'BUKej18sdvI', alt: 'Mages Mazes gameplay' },
    ],
  },
  {
    id:     '36-strategists',
    name:   '36 Strategists',
    tier:   'uncommon',
    badge:  'a',
    status: { type: 'win', label: '✓ Shipped' },
    date:   '2015 – 2016',
    role:   'Programmer',
    studio: 'GD Forge · Kazan · Mobile Turn-Based Strategy · Android',
    desc:   'Mobile adaptation of a classic Chinese strategy board game — turn-based tactics rooted in ancient Chinese military philosophy. 80+ languages, online multiplayer.',
    tags:   ['Mobile', 'Turn-Based', 'Strategy', 'Online Multiplayer'],
    links:  [],
    gallery: [
      { type: 'youtube', videoId: 'QyZCI1gq7Us', alt: '36 Strategists gameplay' },
    ],
  },
];

const SEASONS = [
  {
    season:  'Season 11',
    period:  'Dec 2025 – Now',
    role:    'Senior Client Programmer',
    company: 'GS Studio · Remote',
    points:  ['Quic protocol network refactor', 'EOS integration for online sessions'],
  },
  {
    season:  'Season 10',
    period:  'Jan – Dec 2025',
    role:    'Senior Gameplay Programmer',
    company: 'Majestic Games · Phuket, Thailand',
    points:  ['CommonUI extension system redesign', 'Core gameplay features & editor tools'],
  },
  {
    season:  'Season 8–9',
    period:  'Jun 2023 – Jan 2025',
    role:    'Lead Unreal Engine Programmer',
    company: 'Pixward Games · Phuket, Thailand',
    points:  ['P2P → Client-Server full rearchitect', 'CI/CD · Sentry · EOS · EAC integration', 'Led growing team of programmers'],
  },
  {
    season:  'Season 7',
    period:  'Jun 2022 – Jun 2023',
    role:    'Senior AI Programmer',
    company: 'MY.GAMES · Remote',
    points:  ['HTN planning system & crowd NPCs', 'Nav-links generator for open world'],
  },
  {
    season:  'Season 4–6',
    period:  'Jan 2019 – Jun 2022',
    role:    'Software Engineer',
    company: 'Vizor Games · Minsk, Belarus',
    points:  ['GAS integration & combat abilities', 'CPU optimisation −27% via profiling', 'Automation Spec & Gauntlet test frameworks'],
  },
  {
    season:  'Season 1–3',
    period:  'Nov 2015 – Dec 2018',
    role:    'Game Developer',
    company: 'GD Forge · Kazan, Russia',
    points:  ['Fullstack dev for 2 mobile games (Unity / C#)', 'AI, gameplay & VFX for VR cooperative games on UE4'],
  },
];

const MEDALS = [
  { tier: 't3', icon: 'AAA', name: 'Triple-A Shipped',    desc: 'Contributed to AAA published titles on PC &amp; Console.' },
  { tier: 't3', icon: '⚡',  name: 'Network Architect',   desc: 'Led full P2P → Client-Server migration on a live VR-PC shooter.' },
  { tier: 't3', icon: 'X',   name: 'Decade Veteran',      desc: '10+ years of professional Unreal Engine development.' },
  { tier: 't2', icon: '★',   name: 'Lead Programmer',     desc: 'Led and grew a programmer team at Pixward Games.' },
  { tier: 't2', icon: '−27', name: 'Performance Master',  desc: 'Reduced CPU time by 27% on a shipped UE4 fighter via profiling.' },
  { tier: 't2', icon: 'AI',  name: 'AI Specialist',       desc: 'HTN planning, crowd NPCs, and nav-link generators for open worlds.' },
  { tier: 't1', icon: 'C++', name: 'C++ Expert',          desc: 'Primary language across all 5 studios for a decade.' },
  { tier: 't1', icon: 'VR',  name: 'VR Developer',        desc: 'Shipped VR cooperative titles &amp; an asymmetric VR-PC shooter.' },
  { tier: 't1', icon: '∞',   name: 'CI/CD Engineer',      desc: 'Built pipelines from scratch with Sentry monitoring &amp; EAC.' },
  { tier: 'locked', icon: '?', name: 'Open Source Hero',  desc: 'Publish a public UE plugin or dev tool. <em>In Progress.</em>' },
  { tier: 'locked', icon: '?', name: 'GDC Speaker',       desc: 'Talk at a major industry conference. <em>Career Goal.</em>' },
];

const MEDALS_SUMMARY = [
  { tier: 't3', label: 'Tier 3', count: 3 },
  { tier: 't2', label: 'Tier 2', count: 3 },
  { tier: 't1', label: 'Tier 1', count: 3 },
  { tier: '',   label: 'Locked', count: 2 },
];

const CONTACT = {
  email:        'work.n.galochkin@gmail.com',
  availability: 'Remote · Freelance · Full-time · Available Now',
  links: [
    { label: 'LinkedIn',   url: 'https://www.linkedin.com/in/n-galochkin' },
    { label: 'GitHub',     url: 'https://github.com/n-galochkin' },
    { label: 'Upwork',     url: 'https://www.upwork.com/freelancers/~013b0bb6cd2d2b7969' },
    { label: 'Freelancer', url: 'https://www.freelancer.in/u/RebornAimer' },
  ],
};

const REPORTS = [
  {
    id:      '001',
    cat:     'tech',
    title:   'P2P → Client-Server: Migrating a Live Game\'s Netcode',
    excerpt: 'A practical breakdown of how I rearchitected Boss Fighters\' networking layer from peer-to-peer to authoritative client-server — the gotchas, the wins, and what I\'d do differently.',
    date:    'Coming Soon',
    url:     '#',
  },
  {
    id:      '002',
    cat:     'deepdive',
    title:   'HTN Planning in Open World MMORPG',
    excerpt: 'How we extended Hierarchical Task Networks for a Genshin-style sandbox: new node types, climbing/jumping AI, and a nav-links generator that saved level-designers hours per sprint.',
    date:    'Coming Soon',
    url:     '#',
  },
  {
    id:      '003',
    cat:     'tutorial',
    title:   'Cutting CPU by 27% with Unreal Insights',
    excerpt: 'A step-by-step walkthrough of profiling a shipped UE4 fighter — the tools, the bottlenecks I found, and the changes that delivered measurable, repeatable wins.',
    date:    'Coming Soon',
    url:     '#',
  },
];
